// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-awtQxoqumXbgBdCVG_2wtd0tM-Qx3JM',
    appId: '1:948780151517:web:9bb975015cbaeea4bee134',
    messagingSenderId: '948780151517',
    projectId: 'gamerank-18bd3',
    authDomain: 'gamerank-18bd3.firebaseapp.com',
    storageBucket: 'gamerank-18bd3.firebasestorage.app',
    measurementId: 'G-KKRLW9ND33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7cnbvJNMbzQ8QNG30V_Ug6p82M1cV8M',
    appId: '1:948780151517:android:a07402cd94dbf8e9bee134',
    messagingSenderId: '948780151517',
    projectId: 'gamerank-18bd3',
    storageBucket: 'gamerank-18bd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF5TaqpPnSB5-Yb5ijBMqrjVdgdjV5C-o',
    appId: '1:948780151517:ios:2a0e8b2c69df4282bee134',
    messagingSenderId: '948780151517',
    projectId: 'gamerank-18bd3',
    storageBucket: 'gamerank-18bd3.firebasestorage.app',
    iosBundleId: 'com.example.gameRank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF5TaqpPnSB5-Yb5ijBMqrjVdgdjV5C-o',
    appId: '1:948780151517:ios:2a0e8b2c69df4282bee134',
    messagingSenderId: '948780151517',
    projectId: 'gamerank-18bd3',
    storageBucket: 'gamerank-18bd3.firebasestorage.app',
    iosBundleId: 'com.example.gameRank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-awtQxoqumXbgBdCVG_2wtd0tM-Qx3JM',
    appId: '1:948780151517:web:8f58da963725c1e7bee134',
    messagingSenderId: '948780151517',
    projectId: 'gamerank-18bd3',
    authDomain: 'gamerank-18bd3.firebaseapp.com',
    storageBucket: 'gamerank-18bd3.firebasestorage.app',
    measurementId: 'G-GND81HBMJ9',
  );

}